name: Window 10

on: [workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999


    steps:
    - name: Download
      run: |
        Invoke-WebRequest -Uri https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe -OutFile cloudflared.exe
        mkdir -p "C:\cloudflared_files"
        Move-Item cloudflared.exe "C:\cloudflared_files"
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText ${{ secrets.RDP_PASSWORD }} -Force)
    
    - name: Create Tunnel
      run: |
        & "C:\cloudflared_files\cloudflared.exe" service install ${{ secrets.TUNNEL_SECRET }}
